# Generated by Django 4.1.13 on 2024-05-31 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRecord', models.CharField(max_length=20)),
                ('patientName', models.CharField(max_length=40)),
                ('total', models.CharField(max_length=20)),
                ('medicine', models.CharField(max_length=500)),
                ('fee', models.CharField(max_length=20)),
                ('createdDate', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('idPatient', models.CharField(max_length=20)),
                ('bedFee', models.CharField(max_length=20)),
            ],
        ),
    ]
