# Generated by Django 4.2.11 on 2024-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='createdDay',
            field=models.DateField(auto_now_add=True),
        ),
    ]
