# Generated by Django 4.1.13 on 2024-05-30 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPatient', models.CharField(max_length=20)),
                ('idDoctor', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('idRoom', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=500)),
                ('createdDate', models.DateField(default=django.utils.timezone.now)),
                ('patientName', models.CharField(max_length=50)),
                ('patientContact', models.CharField(max_length=50)),
                ('doctorName', models.CharField(max_length=50)),
                ('doctorContact', models.CharField(max_length=50)),
                ('roomNumber', models.CharField(max_length=50)),
                ('buildingName', models.CharField(max_length=50)),
            ],
        ),
    ]
