# Generated by Django 4.2.11 on 2024-05-30 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provice', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('ward', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=200, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.address')),
                ('fullName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.fullname')),
            ],
        ),
    ]
