# Generated by Django 4.2.11 on 2024-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPayment', models.IntegerField()),
                ('idEmployee', models.IntegerField()),
                ('recipientName', models.CharField(max_length=100)),
                ('createdDay', models.DateField(auto_now_add=True)),
                ('medicine', models.CharField(max_length=100, null=True)),
                ('fee', models.IntegerField()),
                ('bedFee', models.IntegerField()),
                ('paymentDay', models.DateField()),
                ('contact', models.CharField(max_length=200, null=True)),
                ('total', models.IntegerField()),
            ],
        ),
    ]
